name: pi01
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1+2

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  dart_periphery: ^0.9.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  get: ^4.6.6
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    
